version: "3"
services:
  node:
    container_name: node
    build: ./node
    image: abhishek/lab5image
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/node/app
    command: "nodemon -L"

